dist: trusty

jobs:
  include:
    - stage: build 1
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-base-image:latest pyiron-base/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-base-image:latest
      - export TODAY=$(date +%F)
      - docker tag $DOCKER_USERNAME/pyiron-base-image:latest $DOCKER_USERNAME/pyiron-base-image:"$TODAY"
      - docker push $DOCKER_USERNAME/pyiron-base-image:"$TODAY"
    - stage: build 2
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-image:latest pyiron/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-image:latest
      - export TODAY=$(date +%F)
      - docker tag $DOCKER_USERNAME/pyiron-image:latest $DOCKER_USERNAME/pyiron-image:"$TODAY"
      - docker push $DOCKER_USERNAME/pyiron-image:"$TODAY"
    - stage: build 3
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-md-image pyiron-md/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-md-image
      - export TODAY=$(date +%F)
      - docker tag $DOCKER_USERNAME/pyiron-md-image:latest $DOCKER_USERNAME/pyiron-md-image:"$TODAY"
      - docker push $DOCKER_USERNAME/pyiron-md-image:"$TODAY"
    - stage: build 4
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-sphinx-image pyiron-sphinxdft/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-sphinx-image
      - export TODAY=$(date +%F)
      - docker tag $DOCKER_USERNAME/pyiron-sphinx-image:latest $DOCKER_USERNAME/pyiron-sphinx-image:"$TODAY"
      - docker push $DOCKER_USERNAME/pyiron-sphinx-image:"$TODAY"
    - stage: build 5
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-dft-image pyiron-dft/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-dft-image
      - export TODAY=$(date +%F)
      - docker tag $DOCKER_USERNAME/pyiron-dft-image:latest $DOCKER_USERNAME/pyiron-dft-image:"$TODAY"
      - docker push $DOCKER_USERNAME/pyiron-dft-image:"$TODAY"
    - stage: test1
      script: docker run --rm $DOCKER_USERNAME/pyiron-base-image echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-base-image echo hello world
    - stage: test2
      script: docker run --rm $DOCKER_USERNAME/pyiron-image echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-image echo hello world
    - stage: test3
      script: docker run --rm $DOCKER_USERNAME/pyiron-md-image echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-md-image echo hello world
    - stage: test4
      script: docker run --rm $DOCKER_USERNAME/pyiron-sphinx-image echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-sphinx-image echo hello world
    - stage: test5
      script: docker run --rm $DOCKER_USERNAME/pyiron-dft-image echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-dft-image echo hello world