dist: trusty

jobs:
  include:
    - stage: build 1
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-base-image-beta:latest pyiron-base/
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-base-image-beta:latest
      - export today="date +%F"
      - docker tag $DOCKER_USERNAME/pyiron-base-image-beta:latest $DOCKER_USERNAME/pyiron-base-image-beta:$today
      - docker push $DOCKER_USERNAME/pyiron-base-image-beta:$today
    # - stage: build 2
    #   script:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   - docker build -t $DOCKER_USERNAME/pyiron-lammps-image pyiron-lammps/
    #   - docker images
    #   - docker push $DOCKER_USERNAME/pyiron-lammps-image
    # - stage: build 3
    #   script:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   - docker build -t $DOCKER_USERNAME/pyiron-sphinx-gpaw-image pyiron-sphinx-gpaw/
    #   - docker images
    #   - docker push $DOCKER_USERNAME/pyiron-sphinx-gpaw-image
    # - stage: build 4
    #   script:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   - docker build -t $DOCKER_USERNAME/pyiron-lammps-sphinx-gpaw-image pyiron-lammps-sphinx-gpaw/
    #   - docker images
    #   - docker push $DOCKER_USERNAME/pyiron-lammps-sphinx-gpaw-image
    - stage: test1
      script: docker run --rm $DOCKER_USERNAME/pyiron-base-image-beta echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-base-image-beta echo hello world
    # - stage: test2
    #   script: docker run --rm $DOCKER_USERNAME/pyiron-lammps-image echo hello world
    # - script: docker run --rm $DOCKER_USERNAME/pyiron-lammps-image echo hello world
    # - stage: test3
    #   script: docker run --rm $DOCKER_USERNAME/pyiron-lammps-sphinx-gpaw-image echo hello world
    # - script: docker run --rm $DOCKER_USERNAME/pyiron-lammps-sphinx-gpaw-image echo hello world
    # - stage: test4
    #   script: docker run --rm $DOCKER_USERNAME/pyiron-sphinx-gpaw-image echo hello world
    # - script: docker run --rm $DOCKER_USERNAME/pyiron-sphinx-gpaw-image echo hello world
