channels:
- conda-forge
dependencies:
- pyiron =0.5.0
- pyiron_atomistics =0.3.6
- pyscal =2.10.18
- maggma =0.57.10
- pyiron-data =0.0.25
- nglview =3.0.8
- lammps =2023.08.02=*openmpi*
- openkim-models =2021.01.28
