channels:
- conda-forge
dependencies:
- lammps =2021.07.30=*mpich*
- damask =3.0.0a5
- fenics =2019.1.0=*_24
- mshr =2019.1.0
- panel =0.12.6
- pyiron_continuum =0.0.4
- pyiron_gpl =0.0.3
- pymatgen =2022.3.7
- pyvista
- sqsgenerator =0.2
- vtk
