channels:
- conda-forge
dependencies:
- python =3.8*
- lammps =2021.08.31=*mpich*
- damask =3.0.0a4
- vtk
- itkwidgets
- pyvista
- pymatgen =2022.0.16
- sqsgenerator =0.0.5
- fenics =2019.1.0
- mshr =2019.1.0
- pyiron_continuum =0.0.3
- pyiron_gpl =0.0.3
