channels:
- conda-forge
dependencies:
- damask =3.0.0
- vtk
- itkwidgets
- pyvista
- pymatgen =2022.0.6
- sqsgenerator =0.0.5
- fenics =2019.1.0
- mshr =2019.1.0
- pyiron_continuum =0.0.1
- pyiron_gpl =0.0.3

