channels:
- conda-forge
dependencies:
  - fenics =2019.1.0
  - fenics-libdolfin =2019.1.0=*_8
  - mshr =2019.1.0=*_2
  - pyiron =0.3.21
  - nglview =2.7.7
  - matplotlib =3.3.3
  - scikit-image =0.18.0
  - seaborn =0.11.0