channels:
- conda-forge
dependencies:
- sphinxdft =3.0.3
- atomicrex =1.0.2
- runner =1.2
- structdbrest =0.0.1
- pyiron_contrib =0.0.13
- pyiron_gpl =0.0.3
- nbgitpuller =0.10.1
- pip
- pip:
    - pyace-lite
