channels:
- conda-forge
dependencies:
- sphinxdft =2.7.0
- atomicrex =1.0.1
- runner =1.2
- structdbrest =0.0.1
- pyiron_contrib =0.0.5
- pyiron_gpl =0.0.2
- nbgitpuller =0.9.0
- pip
- pip:
    - pyace-lite
