name: Docker Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t pyiron/base:latest base/
      - run: docker tag pyiron/base:latest pyiron/base:"$(date +%F)"
      - run: docker build -t pyiron/md:latest md/
      - run: docker tag pyiron/md:latest pyiron/md:"$(date +%F)"
      - run: docker build -t pyiron/pyiron:latest pyiron/
      - run: docker tag pyiron/pyiron:latest pyiron/pyiron:"$(date +%F)"
      - run: docker build -t pyiron/potentialworkshop:latest potentialworkshop/
      - run: docker tag pyiron/potentialworkshop:latest pyiron/potentialworkshop:"$(date +%F)"
      - run: docker build -t pyiron/experimental:latest experimental/
      - run: docker tag pyiron/experimental:latest pyiron/experimental:"$(date +%F)"
      - run: docker build -t pyiron/continuum:latest continuum/
      - run: docker tag pyiron/continuum:latest pyiron/continuum:"$(date +%F)"
      - run: docker images
      - run: docker push pyiron/base:latest
      - run: docker push pyiron/base:"$(date +%F)"
      - run: docker push pyiron/md:latest
      - run: docker push pyiron/md:"$(date +%F)"
      - run: docker push pyiron/pyiron:latest
      - run: docker push pyiron/pyiron:"$(date +%F)"
      - run: docker push pyiron/potentialworkshop:latest
      - run: docker push pyiron/potentialworkshop:"$(date +%F)"
      - run: docker push pyiron/experimental:latest
      - run: docker push pyiron/experimental:"$(date +%F)"
      - run: docker push pyiron/continuum:latest
      - run: docker push pyiron/continuum:"$(date +%F)"
