name: Docker Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%F)"
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
      - run: docker build -t pyiron/base:latest base/
      - run: docker tag pyiron/base:latest pyiron/base:"$(date +%F)"
      - run: docker build -t pyiron/md:latest md/
      - run: docker tag pyiron/md:latest pyiron/md:"$(date +%F)"
      - run: docker build -t pyiron/continuum:latest continuum/
      - run: docker tag pyiron/continuum:latest pyiron/continuum:"$(date +%F)"
      - run: docker build -t pyiron/pyiron:latest pyiron/
      - run: docker tag pyiron/pyiron:latest pyiron/pyiron:"$(date +%F)"
      - run: docker build -t pyiron/potentialworkshop:latest potentialworkshop/
      - run: docker tag pyiron/potentialworkshop:latest pyiron/potentialworkshop:"$(date +%F)"
      - run: docker build -t pyiron/experimental:latest experimental/
      - run: docker tag pyiron/experimental:latest pyiron/experimental:"$(date +%F)"
      - run: docker images
      - run: docker run --rm pyiron/continuum /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'
      - run: docker run --rm pyiron/base /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'  
      - run: docker run --rm pyiron/pyiron /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'
      - run: docker run --rm pyiron/experimental /bin/bash -c 'source /opt/conda/bin/activate; i=0; for f in $(ls ~/*.ipynb); do jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook --execute $f || i=$((i+1)); done; if [ $i -gt 0 ]; then exit 1; fi;'
      
